### ISSUE TITLE
Roadmap of the package ?

### ISSUE THREAD

**Issue by serkserk** [Luttik/py_process_mining#1]
Hello,

Firstly, this package looks very promising, a good alternative to bupaR (https://www.bupar.net) for process mining in python
I'd like to know plan for this package that you seems to be actively working on ?
Do you have a road map ?

Thanks

**Comment by Luttik** [comment]
Hé I still have to upgrade the readme. But I suggest using [PM4Py](https://github.com/pm4py/pm4py-source) that package was started just 2 weeks ago but has the support of a large part of the academic process mining community (both the Eindhoven University of Technology and RWTH Aachen University seem to contribute). 

My main purpose for this is that I needed it for my thesis and it didn't exist yet, but I will focus on implementing what I've done here into PM4Py to help the community.

**Comment by serkserk** [comment]
OK, that good to know, thanks
